### PR TITLE
`scripts`: Rely on `setup.sh` in build scripts

### PR DESCRIPTION
**Pull request by razvand**
Remove commands to clone repositories from inside build scripts. They are no longer required, since we rely on the user running the local `./setup.sh` script first.

Also add content from PR #20

### CODE REVIEW

**Review by StefanJum — COMMENTED** [review]
Seems fine, will approve after #20 is merged and this is rebased.

**Review by spx01 — APPROVED** [review]

**Review by spx01 — APPROVED** [review]
Reviewed-by: spx01 <42381535+spx01@users.noreply.github.com>

**Review by StefanJum — COMMENTED** [review]
This should be fine, but I'll wait for #20 to be merged and this rebased just to make sure I didn't miss anything.

Same for #22

**Review by spx01 — APPROVED** [review]
Reviewed-by: spx01 42381535+spx01@users.noreply.github.com
Approved-by: spx01 42381535+spx01@users.noreply.github.com

**Pull request merged**
